CREATE TABLE MOVIE_ACTOR
(
    MOVIE_ID INTEGER NOT NULL,
    ACTOR_ID  INTEGER NOT NULL,
    PRIMARY KEY (MOVIE_ID, ACTOR_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID),
    FOREIGN KEY (ACTOR_ID) REFERENCES ACTOR(ID)
);
